[2021-12-22 01:54:38,100] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: Example_2.call_python_sript manual__2021-12-22T01:54:37.734851+00:00 [queued]>
[2021-12-22 01:54:38,118] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: Example_2.call_python_sript manual__2021-12-22T01:54:37.734851+00:00 [queued]>
[2021-12-22 01:54:38,119] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-22 01:54:38,120] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-12-22 01:54:38,121] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-22 01:54:38,165] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): call_python_sript> on 2021-12-22 01:54:37.734851+00:00
[2021-12-22 01:54:38,174] {standard_task_runner.py:52} INFO - Started process 329 to run task
[2021-12-22 01:54:38,186] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Example_2', 'call_python_sript', 'manual__2021-12-22T01:54:37.734851+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/example2.py', '--cfg-path', '/tmp/tmpi2u0y_vi', '--error-file', '/tmp/tmphvhiiilg']
[2021-12-22 01:54:38,187] {standard_task_runner.py:77} INFO - Job 63: Subtask call_python_sript
[2021-12-22 01:54:38,251] {logging_mixin.py:109} INFO - Running <TaskInstance: Example_2.call_python_sript manual__2021-12-22T01:54:37.734851+00:00 [running]> on host 5c1b633758aa
[2021-12-22 01:54:38,410] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Example_2
AIRFLOW_CTX_TASK_ID=call_python_sript
AIRFLOW_CTX_EXECUTION_DATE=2021-12-22T01:54:37.734851+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-22T01:54:37.734851+00:00
[2021-12-22 01:54:38,417] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-12-22 01:54:38,420] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python /opt/***/resources/test.py']
[2021-12-22 01:54:38,453] {subprocess.py:85} INFO - Output:
[2021-12-22 01:54:39,284] {subprocess.py:89} INFO - Empty DataFrame
[2021-12-22 01:54:39,285] {subprocess.py:89} INFO - Columns: [1, 1.1, 1.2]
[2021-12-22 01:54:39,286] {subprocess.py:89} INFO - Index: []
[2021-12-22 01:54:39,347] {subprocess.py:93} INFO - Command exited with return code 0
[2021-12-22 01:54:39,378] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=Example_2, task_id=call_python_sript, execution_date=20211222T015437, start_date=20211222T015438, end_date=20211222T015439
[2021-12-22 01:54:39,454] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-22 01:54:39,501] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
