[2021-12-08 00:15:15,648] {processor.py:163} INFO - Started process (PID=1820) to work on /opt/airflow/dags/example.py
[2021-12-08 00:15:15,675] {processor.py:625} INFO - Processing file /opt/airflow/dags/example.py for tasks to queue
[2021-12-08 00:15:15,695] {logging_mixin.py:109} INFO - [2021-12-08 00:15:15,694] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example.py
[2021-12-08 02:15:11,468] {processor.py:163} INFO - Started process (PID=1838) to work on /opt/airflow/dags/example.py
[2021-12-08 02:15:11,714] {processor.py:625} INFO - Processing file /opt/airflow/dags/example.py for tasks to queue
[2021-12-08 02:15:11,774] {logging_mixin.py:109} INFO - [2021-12-08 02:15:11,772] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example.py
[2021-12-08 02:29:25,393] {processor.py:163} INFO - Started process (PID=1852) to work on /opt/airflow/dags/example.py
[2021-12-08 02:29:25,399] {processor.py:625} INFO - Processing file /opt/airflow/dags/example.py for tasks to queue
[2021-12-08 02:29:25,403] {logging_mixin.py:109} INFO - [2021-12-08 02:29:25,402] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example.py
[2021-12-08 02:29:49,426] {processor.py:637} INFO - DAG(s) dict_keys(['Example']) retrieved from /opt/airflow/dags/example.py
[2021-12-08 02:29:49,666] {logging_mixin.py:109} INFO - [2021-12-08 02:29:49,665] {dag.py:2396} INFO - Sync 1 DAGs
[2021-12-08 02:29:49,880] {logging_mixin.py:109} INFO - [2021-12-08 02:29:49,879] {dag.py:2928} INFO - Setting next_dagrun for Example to 2021-12-07T21:09:14.708986+00:00
[2021-12-08 02:29:49,980] {processor.py:171} INFO - Processing /opt/airflow/dags/example.py took 24.602 seconds
[2021-12-08 02:44:36,375] {processor.py:163} INFO - Started process (PID=1866) to work on /opt/airflow/dags/example.py
[2021-12-08 02:44:36,378] {processor.py:625} INFO - Processing file /opt/airflow/dags/example.py for tasks to queue
[2021-12-08 02:44:36,383] {logging_mixin.py:109} INFO - [2021-12-08 02:44:36,383] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example.py
[2021-12-08 02:44:39,275] {processor.py:637} INFO - DAG(s) dict_keys(['Example']) retrieved from /opt/airflow/dags/example.py
[2021-12-08 02:44:39,382] {logging_mixin.py:109} INFO - [2021-12-08 02:44:39,382] {dag.py:2396} INFO - Sync 1 DAGs
[2021-12-08 02:44:39,457] {logging_mixin.py:109} INFO - [2021-12-08 02:44:39,457] {dag.py:2928} INFO - Setting next_dagrun for Example to 2021-12-07T21:09:14.708986+00:00
[2021-12-08 02:44:39,494] {processor.py:171} INFO - Processing /opt/airflow/dags/example.py took 3.169 seconds
[2021-12-08 02:45:11,083] {processor.py:163} INFO - Started process (PID=1889) to work on /opt/airflow/dags/example.py
[2021-12-08 02:45:11,123] {processor.py:625} INFO - Processing file /opt/airflow/dags/example.py for tasks to queue
[2021-12-08 02:45:11,170] {logging_mixin.py:109} INFO - [2021-12-08 02:45:11,160] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example.py
[2021-12-08 02:45:40,744] {processor.py:637} INFO - DAG(s) dict_keys(['Example']) retrieved from /opt/airflow/dags/example.py
[2021-12-08 02:45:41,636] {logging_mixin.py:109} INFO - [2021-12-08 02:45:41,579] {dag.py:2396} INFO - Sync 1 DAGs
[2021-12-08 02:45:42,411] {logging_mixin.py:109} INFO - [2021-12-08 02:45:42,410] {dag.py:2928} INFO - Setting next_dagrun for Example to 2021-12-07T21:09:14.708986+00:00
[2021-12-08 02:45:42,726] {processor.py:171} INFO - Processing /opt/airflow/dags/example.py took 31.817 seconds
[2021-12-08 02:46:15,131] {processor.py:163} INFO - Started process (PID=1922) to work on /opt/airflow/dags/example.py
[2021-12-08 02:46:15,313] {processor.py:625} INFO - Processing file /opt/airflow/dags/example.py for tasks to queue
[2021-12-08 02:46:15,488] {logging_mixin.py:109} INFO - [2021-12-08 02:46:15,462] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example.py
[2021-12-08 02:46:44,973] {processor.py:637} INFO - DAG(s) dict_keys(['Example']) retrieved from /opt/airflow/dags/example.py
[2021-12-08 02:46:45,324] {logging_mixin.py:109} INFO - [2021-12-08 02:46:45,321] {dag.py:2396} INFO - Sync 1 DAGs
[2021-12-08 02:46:46,223] {logging_mixin.py:109} INFO - [2021-12-08 02:46:46,203] {dag.py:2928} INFO - Setting next_dagrun for Example to 2021-12-07T21:09:14.708986+00:00
[2021-12-08 02:46:47,100] {processor.py:171} INFO - Processing /opt/airflow/dags/example.py took 32.469 seconds
[2021-12-08 02:47:19,282] {processor.py:163} INFO - Started process (PID=1955) to work on /opt/airflow/dags/example.py
[2021-12-08 02:47:19,363] {processor.py:625} INFO - Processing file /opt/airflow/dags/example.py for tasks to queue
[2021-12-08 02:47:19,439] {logging_mixin.py:109} INFO - [2021-12-08 02:47:19,425] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example.py
[2021-12-08 02:47:54,625] {logging_mixin.py:109} INFO - [2021-12-08 02:47:54,521] {timeout.py:36} ERROR - Process timed out, PID: 1955
[2021-12-08 02:47:54,660] {logging_mixin.py:109} WARNING - Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f3e8a2500e0>
[2021-12-08 02:47:54,686] {logging_mixin.py:109} WARNING - Traceback (most recent call last):
[2021-12-08 02:47:54,705] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/weakref.py", line 109, in remove
[2021-12-08 02:47:54,743] {logging_mixin.py:109} WARNING -     def remove(wr, selfref=ref(self), _atomic_removal=_remove_dead_weakref):
[2021-12-08 02:47:54,773] {logging_mixin.py:109} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
[2021-12-08 02:47:54,812] {logging_mixin.py:109} WARNING -     raise AirflowTaskTimeout(self.error_message)
[2021-12-08 02:47:54,905] {logging_mixin.py:109} WARNING - airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/example.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.2/best-practices.html#reducing-dag-complexity, PID: 1955
[2021-12-08 02:48:26,990] {processor.py:163} INFO - Started process (PID=1991) to work on /opt/airflow/dags/example.py
[2021-12-08 02:48:27,017] {processor.py:625} INFO - Processing file /opt/airflow/dags/example.py for tasks to queue
[2021-12-08 02:48:27,157] {logging_mixin.py:109} INFO - [2021-12-08 02:48:27,156] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example.py
[2021-12-08 02:48:57,655] {logging_mixin.py:109} INFO - [2021-12-08 02:48:57,517] {timeout.py:36} ERROR - Process timed out, PID: 1991
[2021-12-08 02:48:58,013] {logging_mixin.py:109} INFO - [2021-12-08 02:48:57,691] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 11, in <module>
    __import__(dependency)
  File "/home/airflow/.local/lib/python3.7/site-packages/numpy/__init__.py", line 148, in <module>
    from . import lib
  File "/home/airflow/.local/lib/python3.7/site-packages/numpy/lib/__init__.py", line 34, in <module>
    from .polynomial import *
  File "/home/airflow/.local/lib/python3.7/site-packages/numpy/lib/polynomial.py", line 968, in <module>
    @array_function_dispatch(_polydiv_dispatcher)
  File "/home/airflow/.local/lib/python3.7/site-packages/numpy/core/overrides.py", line 209, in decorator
    exec(source_object, scope)
  File "<__array_function__ internals>", line 2, in <module>
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/example.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.2/best-practices.html#reducing-dag-complexity, PID: 1991
[2021-12-08 02:48:59,537] {processor.py:673} INFO - Deactivated 1 DAGs which are no longer present in /opt/airflow/dags/example.py
[2021-12-08 02:48:59,560] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example.py
[2021-12-08 02:49:00,402] {processor.py:171} INFO - Processing /opt/airflow/dags/example.py took 34.537 seconds
[2021-12-08 02:49:34,960] {processor.py:163} INFO - Started process (PID=2031) to work on /opt/airflow/dags/example.py
[2021-12-08 02:49:35,786] {processor.py:625} INFO - Processing file /opt/airflow/dags/example.py for tasks to queue
[2021-12-08 02:49:36,275] {logging_mixin.py:109} INFO - [2021-12-08 02:49:36,252] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example.py
[2021-12-08 02:50:20,555] {logging_mixin.py:109} INFO - [2021-12-08 02:50:07,617] {timeout.py:36} ERROR - Process timed out, PID: 2031
[2021-12-08 02:50:54,843] {processor.py:163} INFO - Started process (PID=2048) to work on /opt/airflow/dags/example.py
[2021-12-08 02:50:55,142] {processor.py:625} INFO - Processing file /opt/airflow/dags/example.py for tasks to queue
[2021-12-08 02:50:55,377] {logging_mixin.py:109} INFO - [2021-12-08 02:50:55,302] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example.py
[2021-12-08 02:51:26,708] {logging_mixin.py:109} INFO - [2021-12-08 02:51:26,141] {timeout.py:36} ERROR - Process timed out, PID: 2048
[2021-12-08 02:51:34,661] {logging_mixin.py:109} INFO - [2021-12-08 02:51:26,726] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 11, in <module>
    __import__(dependency)
  File "/home/airflow/.local/lib/python3.7/site-packages/numpy/__init__.py", line 148, in <module>
    from . import lib
  File "/home/airflow/.local/lib/python3.7/site-packages/numpy/lib/__init__.py", line 37, in <module>
    from .npyio import *
  File "/home/airflow/.local/lib/python3.7/site-packages/numpy/lib/npyio.py", line 13, in <module>
    from . import format
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 916, in get_data
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/example.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.2/best-practices.html#reducing-dag-complexity, PID: 2048
[2021-12-08 02:53:10,346] {processor.py:163} INFO - Started process (PID=2077) to work on /opt/airflow/dags/example.py
[2021-12-08 02:53:10,396] {processor.py:625} INFO - Processing file /opt/airflow/dags/example.py for tasks to queue
[2021-12-08 02:53:10,468] {logging_mixin.py:109} INFO - [2021-12-08 02:53:10,449] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example.py
[2021-12-08 02:53:41,010] {logging_mixin.py:109} INFO - [2021-12-08 02:53:40,632] {timeout.py:36} ERROR - Process timed out, PID: 2077
[2021-12-08 02:53:41,473] {logging_mixin.py:109} INFO - [2021-12-08 02:53:41,064] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 11, in <module>
    __import__(dependency)
  File "/home/airflow/.local/lib/python3.7/site-packages/numpy/__init__.py", line 156, in <module>
    from . import random
  File "/home/airflow/.local/lib/python3.7/site-packages/numpy/random/__init__.py", line 179, in <module>
    from . import _pickle
  File "/home/airflow/.local/lib/python3.7/site-packages/numpy/random/_pickle.py", line 1, in <module>
    from .mtrand import RandomState
  File "mtrand.pyx", line 1, in init numpy.random.mtrand
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1052, in exec_module
  File "<frozen importlib._bootstrap>", line 224, in _verbose_message
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/example.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.2/best-practices.html#reducing-dag-complexity, PID: 2077
[2021-12-08 02:53:43,440] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example.py
[2021-12-08 02:53:44,366] {processor.py:171} INFO - Processing /opt/airflow/dags/example.py took 34.823 seconds
[2021-12-08 02:54:21,465] {processor.py:163} INFO - Started process (PID=2125) to work on /opt/airflow/dags/example.py
[2021-12-08 02:54:21,521] {processor.py:625} INFO - Processing file /opt/airflow/dags/example.py for tasks to queue
[2021-12-08 02:54:21,650] {logging_mixin.py:109} INFO - [2021-12-08 02:54:21,643] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example.py
[2021-12-08 02:54:53,284] {logging_mixin.py:109} INFO - [2021-12-08 02:54:52,799] {timeout.py:36} ERROR - Process timed out, PID: 2125
[2021-12-08 02:54:53,361] {logging_mixin.py:109} WARNING - Exception ignored in: <function WeakKeyDictionary.__init__.<locals>.remove at 0x7f3e87190290>
[2021-12-08 02:54:53,371] {logging_mixin.py:109} WARNING - Traceback (most recent call last):
[2021-12-08 02:54:53,382] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/weakref.py", line 358, in remove
[2021-12-08 02:54:53,566] {logging_mixin.py:109} WARNING -     def remove(k, selfref=ref(self)):
[2021-12-08 02:54:53,579] {logging_mixin.py:109} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
[2021-12-08 02:54:54,109] {logging_mixin.py:109} WARNING -     raise AirflowTaskTimeout(self.error_message)
[2021-12-08 02:54:54,331] {logging_mixin.py:109} WARNING - airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/example.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.2/best-practices.html#reducing-dag-complexity, PID: 2125
[2021-12-08 03:28:33,279] {processor.py:163} INFO - Started process (PID=2149) to work on /opt/airflow/dags/example.py
[2021-12-08 03:28:50,558] {processor.py:625} INFO - Processing file /opt/airflow/dags/example.py for tasks to queue
[2021-12-08 03:28:52,129] {logging_mixin.py:109} INFO - [2021-12-08 03:28:52,077] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example.py
[2021-12-08 03:29:56,450] {logging_mixin.py:109} INFO - [2021-12-08 03:29:35,877] {timeout.py:36} ERROR - Process timed out, PID: 2149
[2021-12-08 03:30:01,377] {logging_mixin.py:109} INFO - [2021-12-08 03:30:01,178] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example.py
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.so'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example.py", line 2, in <module>
    import pandas as pd
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1383, in find_spec
  File "<frozen importlib._bootstrap_external>", line 95, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/example.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.2/best-practices.html#reducing-dag-complexity, PID: 2149
[2021-12-08 04:04:23,853] {processor.py:163} INFO - Started process (PID=2165) to work on /opt/airflow/dags/example.py
[2021-12-08 04:04:23,904] {processor.py:625} INFO - Processing file /opt/airflow/dags/example.py for tasks to queue
[2021-12-08 04:04:24,249] {logging_mixin.py:109} INFO - [2021-12-08 04:04:24,213] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example.py
[2021-12-08 06:15:39,970] {processor.py:163} INFO - Started process (PID=2176) to work on /opt/airflow/dags/example.py
[2021-12-08 06:15:40,653] {processor.py:625} INFO - Processing file /opt/airflow/dags/example.py for tasks to queue
[2021-12-08 06:15:41,269] {logging_mixin.py:109} INFO - [2021-12-08 06:15:41,257] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example.py
[2021-12-08 06:15:43,280] {processor.py:163} INFO - Started process (PID=2177) to work on /opt/airflow/dags/example.py
[2021-12-08 06:15:43,390] {processor.py:625} INFO - Processing file /opt/airflow/dags/example.py for tasks to queue
[2021-12-08 06:15:44,284] {logging_mixin.py:109} INFO - [2021-12-08 06:15:44,282] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example.py
[2021-12-08 06:16:34,566] {logging_mixin.py:109} INFO - [2021-12-08 06:16:25,654] {timeout.py:36} ERROR - Process timed out, PID: 2177
[2021-12-08 06:16:36,675] {logging_mixin.py:109} INFO - [2021-12-08 06:16:25,655] {timeout.py:36} ERROR - Process timed out, PID: 2176
[2021-12-08 06:17:44,287] {logging_mixin.py:109} INFO - [2021-12-08 06:17:01,466] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example.py
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/.local/lib/python3.7/site-packages/numpy/__init__.abi3.so'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 11, in <module>
    __import__(dependency)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1383, in find_spec
  File "<frozen importlib._bootstrap_external>", line 95, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/example.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.2/best-practices.html#reducing-dag-complexity, PID: 2177
